name: Update version
on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - ".updatecli/**"
      - "updatecli-compose.yaml"
      - "Containerfile"
      - "Cargo.toml"
      - "package.json"
      - ".forgejo/workflows/updatecli.yml"
permissions:
  contents: write
  pull-requests: write
jobs:
  updatecli:
    runs-on: kubernetes
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Updatecli
        uses: https://github.com/updatecli/updatecli-action@41b9c8d707830a9daebaeaa84c1b62d60b779564 # v3.6.0
      - name: "\U0001F980 Install Rust Toolchain"
        uses: https://github.com/dtolnay/rust-toolchain@d1031067263f94b142dd6c0ce24c5eb9d02d52a0 # v1
        with:
          toolchain: stable
      - name: Setup pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        with:
          version: 11
      - name: Run Updatecli
        run: updatecli compose apply
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
